export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const GET_CHARACTER_DETAIL = "GET_CHARACTER_DETAIL";
export const CLEAN_CHARACTER_DETAIL = "CLEAN_CHARACTER_DETAIL";
export const SEARCH_CHARACTER_DETAIL = "SEARCH_CHARACTER_DETAIL";
export const GET_BACK = "GET_BACK";
export const CLOSE = "CLOSE";